# Generated by Django 5.2.5 on 2025-10-13 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('Valparaíso', 'Valparaíso'), ('Marga Marga', 'Marga Marga'), ('Quillota', 'Quillota'), ('Petorca', 'Petorca'), ('San Antonio', 'San Antonio'), ('San Felipe de Aconcagua', 'San Felipe de Aconcagua'), ('Los Andes', 'Los Andes'), ('Isla de Pascua', 'Isla de Pascua')], max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('orientacion_terreno', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], max_length=50)),
                ('pendiente_terreno', models.CharField(choices=[('Plana', 'Plana'), ('Moderada', 'Moderada'), ('Empinada', 'Empinada')], max_length=50)),
                ('exposicion_solar', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=50)),
                ('velocidad_viento', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=50)),
                ('tipo_suelo', models.CharField(choices=[('Rocoso', 'Rocoso'), ('Arenoso', 'Arenoso'), ('Arcilloso', 'Arcilloso'), ('Mixto', 'Mixto')], max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
