# Generated by Django 5.1.1 on 2025-11-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_provinciadatos_delete_datosterreno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('estructura', 'Estructura y obra gruesa'), ('aislacion', 'Aislamiento térmico y acústico'), ('muros', 'Muros y tabiquería'), ('cubiertas', 'Cubiertas y techos'), ('maderas', 'Maderas y acabados'), ('revestimientos', 'Revestimientos y pisos'), ('instalaciones', 'Instalaciones y eficiencia energética'), ('naturales', 'Muros y soluciones naturales'), ('ventanas', 'Ventanas y carpinterías'), ('sistemas', 'Sistemas complementarios')], max_length=50, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
