# Generated by Django 5.2.8 on 2025-11-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='relevancia_radiacion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Relevancia del material frente a radiación (0=nula, 3=alta).', verbose_name='Relevancia para Radiación Solar'),
        ),
        migrations.AddField(
            model_name='material',
            name='relevancia_temperatura',
            field=models.PositiveSmallIntegerField(default=0, help_text='Relevancia del material frente a temperaturas (0=nula, 3=alta).', verbose_name='Relevancia para Temperatura'),
        ),
        migrations.AddField(
            model_name='material',
            name='relevancia_viento',
            field=models.PositiveSmallIntegerField(default=0, help_text='Relevancia del material frente al viento (0=nula, 3=alta).', verbose_name='Relevancia para Viento'),
        ),
    ]
