# Generated by Django 5.2.5 on 2025-11-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_material_relevancia_radiacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinciadatos',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='provincia_datos', to='materiales.material'),
        ),
    ]
