# Generated by Django 5.1.1 on 2025-11-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.CharField(choices=[('estructura', 'Estructura y obra gruesa'), ('aislacion', 'Aislamiento térmico y acústico'), ('muros', 'Muros y tabiquería'), ('cubiertas', 'Cubiertas y techos'), ('maderas', 'Maderas y acabados'), ('revestimientos', 'Revestimientos y pisos'), ('instalaciones', 'Instalaciones y eficiencia energética'), ('naturales', 'Muros y soluciones naturales'), ('ventanas', 'Ventanas y carpinterías'), ('sistemas', 'Sistemas complementarios')], default='estructura', max_length=50, verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
